% -------------------------------------------------------------------
%  Generated by MATLAB on 11-May-2026 13:06:46
%  MATLAB version: 26.1.0.3234472 (R2026a) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('lab04_taylor.mat');

N = 2000;

T = 2;

X = saveVarsMat.X; % <1x2000 double> too many elements

X_mag = saveVarsMat.X_mag; % <1x1001 double> too many elements

f = saveVarsMat.f; % <1x1001 double> too many elements

fs = 1000;

i = 2;

locs = [101 275];

pks = [0.35067783276987108 0.15039618594772963];

t = saveVarsMat.t; % <1x2000 double> too many elements

w = saveVarsMat.w; % <1x2000 double> too many elements

x = saveVarsMat.x; % <1x2000 double> too many elements

xw = saveVarsMat.xw; % <1x2000 double> too many elements

clear saveVarsMat;
